spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 80
#Eureka配置
eureka:
  client:
    register-with-eureka: false  #不在eureka注册自己
    service-url:
     defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
#开启降级
feign:
  hystrix:
    enabled: true
---
spring:
  profiles: test
server:
  port: 80
#Eureka配置
eureka:
  client:
    register-with-eureka: false  #不在eureka注册自己
    service-url:
     defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
#开启降级

feign:
  hystrix:
    enabled: true